pull_request_rules:
  - name: automatic merge dependabot PRs into dev
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        strict_method: rebase
  - name: delete head branch on merged pull requests
    conditions:
      - merged
      - -head~=^(master|dev)$
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      delete_head_branch:
  - name: merge PRs labeled ready-to-merge
    conditions:
      - status-success=Finish Test
      - label=ready-to-merge
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        strict_method: merge
