language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "stable"
env:
  matrix:
  - TEST_SUITE=build
cache:
  directories:
  - node_modules
script:
- npm run test:$TEST_SUITE
jobs:
  include:
  - stage: github pages release
    node_js: 'stable'
    script: npm run build:webpack
    if: branch = master
    deploy:
      provider: pages
      skip-cleanup: true
      local-dir: build
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
        
