name: Deploy to Github Pages
on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Patch NPM
        run: |
          npm install -g npm
      - name: Install
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Build
        run: |
          npx lerna run build
          cp ./packages/client/dist/browser/index.html ./packages/client/dist/browser/404.html
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.APP_DEPLOY_KEY }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: master # The branch the action should deploy to.
          FOLDER: packages/client/dist/browser # The folder the action should deploy.
          REPOSITORY_NAME: spielhalle/spielhalle.github.io
          TARGET_FOLDER: .
          CLEAN: true
  build-docs-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Documentation
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Patch NPM
        run: |
          npm install -g npm
      - name: Install and Build 🔧
        run: |
          npm ci
          npx lerna bootstrap --ci
          npx lerna run build
          npx lerna run docs
          node .github/workflows/prepare_docs_deploy.js
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DOCS_DEPLOY_KEY }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: master # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          REPOSITORY_NAME: spielhalle/docs
          TARGET_FOLDER: .
